---
# tasks file for install-jenkins

- name: Install software-properties-common
  apt:
    name: software-properties-common
    update_cache: yes
    state: present

- name: Add Ansible repo
  apt_repository:
    repo: ppa:ansible/ansible

- name: Install Ansible
  apt:
    name: ansible
    update_cache: yes
    state: present

- name: Install PIP
  apt:
    name: python-pip
    update_cache: yes
    state: present

- name: Install BOTO3
  pip:
    name: boto3

- name: Install BOTO
  pip:
    name: boto

